language: node_js
sudo: false
node_js:
  - "8.12.0"
env:
    - TELEGRAM_BOT_TOKEN=123:TEST
install:
  - npm install
  - pyenv global 3.6.3
  - pip3 install rx
  - pip3 install numpy
script:
  - npm test
  - npm run lint
after_success:
  - ./node_modules/.bin/nyc --reporter=lcov --reporter=text-lcov npm test > nyc-coverage.lcov
  - ./node_modules/.bin/codecov -f nyc-coverage.lcov
